In [103]:
import numpy as np

In [104]:
x = np.arange(16)

In [105]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [106]:
type(x)

numpy.ndarray

In [107]:
x.size

16

In [108]:
x.shape

(16,)

In [109]:
x1 = x.reshape(4,4)

In [110]:
x1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
# x.reshape(3,3) would return an error

In [112]:
x3 = x.reshape(2,2,4)

In [113]:
x3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [114]:
# no. of square brackets can tell you how many dimensions in an array

In [115]:
x4 = x.reshape(2,2,2,2)

In [116]:
x4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [117]:
x1[2,2]

10

In [118]:
x1[1:,::2] = -99 # row 1 kay baad say har dosra column wali index ko -99 ki valye di

In [119]:
x1

array([[  0,   1,   2,   3],
       [-99,   5, -99,   7],
       [-99,   9, -99,  11],
       [-99,  13, -99,  15]])

In [120]:
x1.max()

15

In [121]:
x1.max(axis=0) # max from each row

array([ 0, 13,  2, 15])

In [122]:
x1.max(axis=1) # max from each column

array([ 3,  7, 11, 15])

In [123]:
arr = np.arange(16).reshape(4,4) #aik he line main x1 bana diya

In [124]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [125]:
y= np.zeros((4,4))

In [126]:
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [127]:
z = np.ones((4,4))

In [128]:
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [129]:
#ones and zeroes are the only one that exists

In [130]:
w = np.empty([2,4,4])

In [131]:
w

array([[[1.50751130e-311, 1.06224114e-321, 0.00000000e+000,
         0.00000000e+000],
        [7.56587583e-307, 5.02034658e+175, 7.86349968e-067,
         4.98774866e-037],
        [2.03829412e+160, 2.23290522e+180, 4.95212552e-062,
         4.26490098e-096],
        [1.12855837e+277, 8.93168725e+271, 4.76484771e+180,
         2.59027921e-144]],

       [[3.80985069e+180, 1.14428494e+243, 2.59027907e-144,
         7.79952704e-143],
        [1.59990973e+160, 1.40483432e+165, 7.79495320e-071,
         1.17029025e-046],
        [2.59027858e-144, 2.59903818e-144, 5.58166873e-091,
         5.35653487e-038],
        [1.04119841e-042, 1.11475752e+261, 1.16318408e-028,
         2.59297589e-306]]])

In [132]:
#empty doesnt make an actually empty array, it just fills it with random values

In [133]:
np.full([2,3],44)

array([[44, 44, 44],
       [44, 44, 44]])

In [134]:
ls = [22,'python','location',4.4]
arr = np.array(ls)

In [135]:
arr

array(['22', 'python', 'location', '4.4'], dtype='<U32')

In [136]:
# u usually shudnt mix datatyoes in arrays cuz numpy will use some other datatype that they have e.g they used u23 here and ion know what that is

In [137]:
z.ndim

2

In [138]:
a = np.arange(6,14,2).reshape(2,2) # start from 6  end is 14 (not included in array so uptil 12), steps 2. Reshape array to 2x2

In [139]:
a

array([[ 6,  8],
       [10, 12]])

In [140]:
b = np.arange(6,14,2).reshape(2,2)

In [141]:
a*b

array([[ 36,  64],
       [100, 144]])

In [142]:
a-b

array([[0, 0],
       [0, 0]])

In [143]:
a+3

array([[ 9, 11],
       [13, 15]])

In [144]:
a*3

array([[18, 24],
       [30, 36]])

In [145]:
# boolean operator check

In [146]:
a[a%3 == 0] # returns numbers which when divided by three have a remainder of 0 (modulus used)

array([ 6, 12])

In [147]:
a[a%3 != 0] # returns numbers which when divided by three dont have a remainder of 0 (modulus used)

array([ 8, 10])

In [148]:
values = np.random.randn(3,3)

In [149]:
values

array([[ 0.15146226, -0.25063133, -1.68571252],
       [-0.10896468, -0.32024034,  0.73273915],
       [-0.4384145 ,  0.3655638 ,  1.17002186]])

In [150]:
data = np.array([['cat','dog','cat',],['dog','dog','cat'],['cat','cat','dog']])

In [151]:
data

array([['cat', 'dog', 'cat'],
       ['dog', 'dog', 'cat'],
       ['cat', 'cat', 'dog']], dtype='<U3')

In [152]:
values[data=='cat'] # if data is taken as a data set and values array is corresponding to it, this will find the values assigned to cat

array([ 0.15146226, -1.68571252,  0.73273915, -0.4384145 ,  0.3655638 ])

In [153]:
arr = np.random.randn(10,10)

In [154]:
print(arr)

[[ 0.56866167  0.01248394 -0.45797834 -0.20960358  0.92707364  0.6471591
  -1.07879261  0.44755687  0.44969837 -0.53625323]
 [ 1.14497086  0.65027712  0.73319765 -0.64515596  0.52624331 -0.97564699
  -0.22480557  0.33123591  0.65785461  1.35109668]
 [ 1.28094588 -0.83258896 -0.51366794  1.34626274  0.09034566 -0.80810815
   0.0133519   0.80169093  1.24775066 -0.76922664]
 [-1.11324587  0.51380889 -0.08922818  0.7035953   0.26620443  0.80026763
  -1.89888656  1.03519101 -0.02531945  1.44412972]
 [ 0.20798369  0.34182871  0.25133909  0.34890361 -0.0604516  -0.9479312
   0.18833265 -0.09915154  0.16854181  0.1426806 ]
 [ 1.24448686 -1.61843589 -0.89877568 -0.50090186  1.32010946 -0.6915877
   0.59335717 -0.51710785 -2.57530612 -0.13987834]
 [-1.3617015  -0.01337416 -0.68656456  0.22054519  0.20304936 -2.9071026
   0.60587273 -1.49615009 -0.4808968   0.75784991]
 [-1.22324845  0.24148416  1.13678376  2.02556684 -0.18172111  0.21670263
  -0.86454553 -1.29806341 -0.12796591 -1.45917621]
 [ 0

In [155]:
print(np.round(arr,2))
arr = np.round(arr,2)

[[ 0.57  0.01 -0.46 -0.21  0.93  0.65 -1.08  0.45  0.45 -0.54]
 [ 1.14  0.65  0.73 -0.65  0.53 -0.98 -0.22  0.33  0.66  1.35]
 [ 1.28 -0.83 -0.51  1.35  0.09 -0.81  0.01  0.8   1.25 -0.77]
 [-1.11  0.51 -0.09  0.7   0.27  0.8  -1.9   1.04 -0.03  1.44]
 [ 0.21  0.34  0.25  0.35 -0.06 -0.95  0.19 -0.1   0.17  0.14]
 [ 1.24 -1.62 -0.9  -0.5   1.32 -0.69  0.59 -0.52 -2.58 -0.14]
 [-1.36 -0.01 -0.69  0.22  0.2  -2.91  0.61 -1.5  -0.48  0.76]
 [-1.22  0.24  1.14  2.03 -0.18  0.22 -0.86 -1.3  -0.13 -1.46]
 [ 0.63  0.46  0.76 -0.88 -0.01 -0.39 -1.32  0.2  -0.32  2.06]
 [-1.03 -2.04  2.19 -1.09  0.33  1.63 -0.47 -0.78 -0.96  1.77]]


In [156]:
print(arr[0:10,1]) # printing column 1

[ 0.01  0.65 -0.83  0.51  0.34 -1.62 -0.01  0.24  0.46 -2.04]


In [157]:
print(arr[0,0:10]) #printing row 1

[ 0.57  0.01 -0.46 -0.21  0.93  0.65 -1.08  0.45  0.45 -0.54]


In [158]:
print(arr[0:10:2]) # printing every second row

[[ 0.57  0.01 -0.46 -0.21  0.93  0.65 -1.08  0.45  0.45 -0.54]
 [ 1.28 -0.83 -0.51  1.35  0.09 -0.81  0.01  0.8   1.25 -0.77]
 [ 0.21  0.34  0.25  0.35 -0.06 -0.95  0.19 -0.1   0.17  0.14]
 [-1.36 -0.01 -0.69  0.22  0.2  -2.91  0.61 -1.5  -0.48  0.76]
 [ 0.63  0.46  0.76 -0.88 -0.01 -0.39 -1.32  0.2  -0.32  2.06]]


In [159]:
print(arr[::,0:10:2]) #printing every second column

[[ 0.57 -0.46  0.93 -1.08  0.45]
 [ 1.14  0.73  0.53 -0.22  0.66]
 [ 1.28 -0.51  0.09  0.01  1.25]
 [-1.11 -0.09  0.27 -1.9  -0.03]
 [ 0.21  0.25 -0.06  0.19  0.17]
 [ 1.24 -0.9   1.32  0.59 -2.58]
 [-1.36 -0.69  0.2   0.61 -0.48]
 [-1.22  1.14 -0.18 -0.86 -0.13]
 [ 0.63  0.76 -0.01 -1.32 -0.32]
 [-1.03  2.19  0.33 -0.47 -0.96]]


In [160]:
print(arr[::2]) #another way to print every second row

[[ 0.57  0.01 -0.46 -0.21  0.93  0.65 -1.08  0.45  0.45 -0.54]
 [ 1.28 -0.83 -0.51  1.35  0.09 -0.81  0.01  0.8   1.25 -0.77]
 [ 0.21  0.34  0.25  0.35 -0.06 -0.95  0.19 -0.1   0.17  0.14]
 [-1.36 -0.01 -0.69  0.22  0.2  -2.91  0.61 -1.5  -0.48  0.76]
 [ 0.63  0.46  0.76 -0.88 -0.01 -0.39 -1.32  0.2  -0.32  2.06]]


In [161]:
print(arr[::,::2]) #another way to print every second column

[[ 0.57 -0.46  0.93 -1.08  0.45]
 [ 1.14  0.73  0.53 -0.22  0.66]
 [ 1.28 -0.51  0.09  0.01  1.25]
 [-1.11 -0.09  0.27 -1.9  -0.03]
 [ 0.21  0.25 -0.06  0.19  0.17]
 [ 1.24 -0.9   1.32  0.59 -2.58]
 [-1.36 -0.69  0.2   0.61 -0.48]
 [-1.22  1.14 -0.18 -0.86 -0.13]
 [ 0.63  0.76 -0.01 -1.32 -0.32]
 [-1.03  2.19  0.33 -0.47 -0.96]]


In [162]:
x = np.array([0,1,44,3,67])

In [163]:
x

array([ 0,  1, 44,  3, 67])

In [164]:
y = np.array([2,0,43,30,67])

In [165]:
y

array([ 2,  0, 43, 30, 67])

In [166]:
np.maximum(x,y) # returns an array containing the maximum value at each index between x and y e.g at index 1 x has 0 while y has 2 so 2 is returned

array([ 2,  1, 44, 30, 67])

In [167]:
x = np.arange(9).reshape(3,3)

In [168]:
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [169]:
y = np.arange(6).reshape(3,2)

In [170]:
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [171]:
# x*y wud give error as dimensions not same

In [172]:
np.dot(x,y) # dot product

array([[10, 13],
       [28, 40],
       [46, 67]])

In [173]:
x.dot(y) # another way of doing it

array([[10, 13],
       [28, 40],
       [46, 67]])

In [174]:
x.T # transpose

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [175]:
# transpose means make rows columns and columns rows

In [176]:
x.flatten() # makes array 1D

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [177]:
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [178]:
y

array([[0, 1],
       [2, 3],
       [4, 5]])

In [179]:
y.reshape(2,-1) # u can use -1 to find out second dimension kya banti hai if u dont know urself

array([[0, 1, 2],
       [3, 4, 5]])

In [180]:
# for example above it assiged 2x3

In [181]:
np.concatenate((x,y),axis=1) # column concatenate

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3],
       [6, 7, 8, 4, 5]])

In [182]:
# row concatination doesn't work as there are tthe same number of columns in the rows of x and y however colum wise does work because both have 3 rows in each column

In [183]:
a = np.arange(9).reshape(3,3)

In [184]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [185]:
b= np.arange(10,19).reshape(3,3)

In [186]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [187]:
np.concatenate((a,b),axis=0) # row concatentation

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [188]:
np.hstack((x,y))

array([[0, 1, 2, 0, 1],
       [3, 4, 5, 2, 3],
       [6, 7, 8, 4, 5]])

In [189]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])